version: 2

models:
  - name: dim_property
    columns:
      - name: property_id
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: date_day
        tests:
          - not_null
          - unique

  - name: fact_property_snapshot
    columns:
      - name: property_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_property')
                field: property_id
      - name: snapshot_date
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_date')
                field: date_day
      - name: price
        tests:
          - not_null
      - name: living_area
        tests:
          - not_null
      - name: listing_status
        tests:
          - not_null
      - name: bedrooms
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - property_id
              - snapshot_date

  - name: mart_property_current
    columns:
      - name: property_id
        tests:
          - not_null
          - unique

  - name: mart_market_summary
    columns:
      - name: vegas_district
        tests:
          - not_null
      - name: snapshot_date
        tests:
          - not_null
      - name: listing_count
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - vegas_district
              - snapshot_date
