version: 2

models:
  - name: dim_property
    config:
      tags: ["daily", "gold", "dimension"]
    columns:
      - name: property_id
        data_tests:
          - not_null
          - unique

  - name: dim_date
    config:
      tags: ["one-time", "gold", "dimension"]
    columns:
      - name: date_day
        data_tests:
          - not_null
          - unique

  - name: fact_property_snapshot
    config:
      tags: ["daily", "gold", "fact", "incremental"]
    columns:
      - name: property_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_property')
              field: property_id
      - name: snapshot_date
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_day
      - name: price
        data_tests:
          - not_null
      - name: living_area
        data_tests:
          - not_null
      - name: listing_status
        data_tests:
          - not_null
      - name: bedrooms
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - property_id
            - snapshot_date

  - name: mart_property_current
    config:
      tags: ["daily", "gold", "mart"]
    columns:
      - name: property_id
        data_tests:
          - not_null
          - unique

  - name: mart_market_summary
    config:
      tags: ["daily", "gold", "mart"]
    columns:
      - name: vegas_district
        data_tests:
          - not_null
      - name: snapshot_date
        data_tests:
          - not_null
      - name: listing_count
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - vegas_district
            - snapshot_date
