version: 2

models:
  - name: stg_zillow_property_master
    columns:
      - name: property_sk
        tests:
          - not_null
          - unique
      - name: zpid
        tests:
          - not_null
      - name: extracted_at
        tests:
          - not_null
      - name: snapshot_date
        tests:
          - not_null
      - name: source_file_key
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - zpid
              - source_file_key

  - name: int_zillow_property_history
    columns:
      - name: property_sk
        tests:
          - not_null
          - unique

  - name: int_zillow_property_latest
    columns:
      - name: zpid
        tests:
          - not_null
          - unique
