version: 2

models:
  - name: stg_zillow_property_master
    config:
      tags: ["daily", "silver"]
    columns:
      - name: property_sk
        data_tests:
          - not_null
          - unique
      - name: zpid
        data_tests:
          - not_null
      - name: extracted_at
        data_tests:
          - not_null
      - name: snapshot_date
        data_tests:
          - not_null
      - name: source_file_key
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - zpid
            - source_file_key

  - name: int_zillow_property_history
    config:
      tags: ["daily", "silver", "incremental"]
    columns:
      - name: property_sk
        data_tests:
          - not_null
          - unique

  - name: int_zillow_property_latest
    config:
      tags: ["daily", "silver"]
    columns:
      - name: zpid
        data_tests:
          - not_null
          - unique
